"""
utils/db.py  —  MongoDB persistence layer for EMOTUNE
======================================================
Provides a clean abstraction over all database operations.
No raw MongoDB/BSON code should appear anywhere in app.py.

Collection:  emotune.songs
Schema (one document per saved song):

{
  "_id"            : ObjectId,          # auto-generated by MongoDB
  "song_id"        : str,               # human-readable short ID  (e.g. "EMO-A1B2C3D4")
  "created_at"     : datetime (UTC),    # creation timestamp

  # ── Input ──────────────────────────────────────────────────────────────
  "story_prompt"   : str,               # original user story / inspiration text

  # ── Emotion analysis ───────────────────────────────────────────────────
  "emotion"        : {
      "primary_emotion"   : str,        # "Happy" | "Sad" | "Romantic" | …
      "emotion_intensity" : float,      # 0.0 – 1.0
      "confidence"        : float,      # 0.0 – 1.0
      ...                               # any extra keys returned by detect_emotion()
  },

  # ── Generated content ──────────────────────────────────────────────────
  "lyrics"         : str,               # final Hindi lyrics (possibly user-edited)

  # ── Music parameters ───────────────────────────────────────────────────
  "music_params"   : {
      "mood"        : str,
      "tempo"       : str,
      "genre"       : str,
      "voice_type"  : str,
      "pitch"       : str,
      "tags"        : str,              # full style-prompt string sent to PiAPI
  },

  # ── Output ─────────────────────────────────────────────────────────────
  "audio_url"      : str | None,        # PiAPI CDN URL for the rendered mp3

  # ── User feedback ──────────────────────────────────────────────────────
  "rating"         : int | None,        # 1-5 stars; None until the user rates
}

All public functions return (value, error_str | None).
When error_str is not None the operation failed; value is a safe empty default.
No function ever raises an exception to the caller.
"""

from __future__ import annotations

import os
import uuid
from datetime import datetime, timezone

from dotenv import load_dotenv

# ── Optional pymongo import ────────────────────────────────────────────────
try:
    from pymongo import MongoClient, DESCENDING
    from pymongo.errors import ConnectionFailure, ServerSelectionTimeoutError
    from bson import ObjectId
    _PYMONGO_OK = True
except ImportError:
    _PYMONGO_OK = False


# ── Connection singleton ───────────────────────────────────────────────────
_client = None
_db     = None


def _get_db():
    """
    Return (db_handle, None) on success or (None, error_str) on failure.
    Caches the connection so only one MongoClient is created per process.
    """
    global _client, _db

    if not _PYMONGO_OK:
        return None, (
            "pymongo is not installed. "
            "Run:  pip install pymongo==4.7.2 dnspython==2.6.1"
        )

    # Return cached handle if already connected
    if _db is not None:
        return _db, None

    load_dotenv(override=True)
    uri     = os.getenv("MONGODB_URI", "").strip()
    db_name = os.getenv("MONGODB_DB_NAME", "emotune").strip() or "emotune"

    if not uri or uri == "your_mongodb_connection_string_here":
        return None, (
            "MONGODB_URI is not configured. "
            "Open .env and set:  MONGODB_URI=mongodb+srv://user:pass@cluster.mongodb.net/"
        )

    try:
        # Try standard connection, certifi, or tlsAllowInvalidCertificates fallback
        try:
            _client = MongoClient(uri, serverSelectionTimeoutMS=5_000)
            _client.admin.command("ping")
        except Exception:
            try:
                import certifi
                _client = MongoClient(uri, serverSelectionTimeoutMS=5_000, tlsCAFile=certifi.where())
                _client.admin.command("ping")
            except Exception:
                _client = MongoClient(uri, serverSelectionTimeoutMS=5_000, tlsAllowInvalidCertificates=True)
                _client.admin.command("ping")

        _db = _client[db_name]

        # Ensure useful indexes exist (idempotent)
        _db["songs"].create_index([("created_at", DESCENDING)])
        _db["songs"].create_index("song_id", unique=True)

        return _db, None

    except (ConnectionFailure, ServerSelectionTimeoutError) as exc:
        _client = _db = None
        err_str = str(exc)
        if "TLSV1_ALERT_INTERNAL_ERROR" in err_str or "SSL handshake failed" in err_str:
            return None, (
                "MongoDB Atlas IP Whitelist Error: Your current IP address is not whitelisted in MongoDB Atlas.\n\n"
                "How to fix:\n"
                "1. Go to https://cloud.mongodb.com and log in.\n"
                "2. In the left menu under 'Security', click 'Network Access'.\n"
                "3. Click '+ Add IP Address'.\n"
                "4. Click 'Allow Access from Anywhere' (0.0.0.0/0) or 'Add Current IP Address'.\n"
                "5. Click 'Confirm' and wait 1 minute for rule changes to take effect."
            )
        return None, f"MongoDB connection failed: {exc}"
    except Exception as exc:
        _client = _db = None
        return None, f"Unexpected DB error: {exc}"


# ── Status helpers ─────────────────────────────────────────────────────────

def is_db_connected() -> bool:
    """Return True if the database is reachable."""
    db, _ = _get_db()
    return db is not None


def get_connection_error() -> str | None:
    """Return the human-readable error string, or None when connected."""
    _, err = _get_db()
    return err


# ── ID helpers ─────────────────────────────────────────────────────────────

def _make_song_id() -> str:
    """Generate a short readable ID like EMO-A1B2C3D4."""
    return "EMO-" + uuid.uuid4().hex[:8].upper()


def _doc_to_dict(doc: dict) -> dict:
    """Convert a raw MongoDB document to a JSON-safe Python dict."""
    doc["_id"]    = str(doc["_id"])
    created       = doc.get("created_at")
    if isinstance(created, datetime):
        doc["created_at_str"] = created.strftime("%d %b %Y  %I:%M %p UTC")
    else:
        doc["created_at_str"] = str(created)[:16]
    return doc


# ── Write operations ───────────────────────────────────────────────────────

def save_song(
    story_prompt : str,
    emotion      : dict,
    lyrics       : str,
    music_params : dict,
    audio_url    : str | None = None,
) -> tuple[str | None, str | None]:
    """
    Persist a newly rendered song.

    Returns (song_id_str, None) on success, (None, error_str) on failure.
    song_id_str is the human-readable "EMO-XXXXXXXX" identifier.
    """
    db, err = _get_db()
    if db is None:
        return None, err

    song_id = _make_song_id()

    doc = {
        "song_id"      : song_id,
        "created_at"   : datetime.now(timezone.utc),
        "story_prompt" : story_prompt or "",
        "emotion"      : emotion      or {},
        "lyrics"       : lyrics       or "",
        "music_params" : {
            "mood"       : music_params.get("mood",       ""),
            "tempo"      : music_params.get("tempo",      ""),
            "genre"      : music_params.get("genre",      ""),
            "voice_type" : music_params.get("voice_type", ""),
            "pitch"      : music_params.get("pitch",      ""),
            "tags"       : music_params.get("tags",       ""),
        },
        "audio_url"    : audio_url,
        "rating"       : None,
    }

    try:
        db["songs"].insert_one(doc)
        return song_id, None
    except Exception as exc:
        return None, f"Failed to save song: {exc}"


def update_song_rating(song_id: str, rating: int) -> tuple[bool, str | None]:
    """
    Set or update the user rating (1–5) for a song by its song_id string.

    Returns (True, None) on success, (False, error_str) on failure.
    """
    if rating not in range(1, 6):
        return False, "Rating must be an integer between 1 and 5."

    db, err = _get_db()
    if db is None:
        return False, err

    try:
        result = db["songs"].update_one(
            {"song_id": song_id},
            {"$set": {"rating": rating}},
        )
        if result.matched_count == 0:
            return False, f"No song found with id '{song_id}'."
        return True, None
    except Exception as exc:
        return False, f"Failed to update rating: {exc}"


def delete_song(song_id: str) -> tuple[bool, str | None]:
    """
    Permanently delete a song by its human-readable song_id.

    Returns (True, None) on success, (False, error_str) on failure.
    """
    db, err = _get_db()
    if db is None:
        return False, err

    try:
        result = db["songs"].delete_one({"song_id": song_id})
        if result.deleted_count == 1:
            return True, None
        return False, f"No song found with id '{song_id}'."
    except Exception as exc:
        return False, f"Delete failed: {exc}"


# ── Read operations ────────────────────────────────────────────────────────

def get_recent_songs(limit: int = 50) -> tuple[list[dict], str | None]:
    """
    Fetch the most recent songs, newest first.

    Returns (list_of_dicts, None) on success, ([], error_str) on failure.
    Each dict is JSON-safe (ObjectId → str, datetime formatted).
    """
    db, err = _get_db()
    if db is None:
        return [], err

    try:
        cursor = (
            db["songs"]
            .find({}, sort=[("created_at", DESCENDING)])
            .limit(limit)
        )
        return [_doc_to_dict(doc) for doc in cursor], None
    except Exception as exc:
        return [], f"Failed to fetch songs: {exc}"


def get_song_by_id(song_id: str) -> tuple[dict | None, str | None]:
    """
    Fetch a single song by its human-readable song_id.

    Returns (doc_dict, None) or (None, error_str).
    """
    db, err = _get_db()
    if db is None:
        return None, err

    try:
        doc = db["songs"].find_one({"song_id": song_id})
        if doc is None:
            return None, f"Song '{song_id}' not found."
        return _doc_to_dict(doc), None
    except Exception as exc:
        return None, f"Failed to fetch song: {exc}"


# ── Feature 5: Evaluation Operations ───────────────────────────────────────

def save_evaluation(
    song_id: str,
    emotion_alignment: int,
    lyric_quality: int,
    music_quality: int,
    overall_satisfaction: int,
    feedback_text: str = "",
) -> tuple[bool, str | None]:
    """
    Save or update human/user evaluation metrics for a song.
    """
    for val, name in [
        (emotion_alignment, "Emotion-Lyrics Alignment"),
        (lyric_quality, "Hindi Lyrics Quality"),
        (music_quality, "Music Quality"),
        (overall_satisfaction, "Overall Satisfaction"),
    ]:
        if val not in range(1, 6):
            return False, f"{name} rating must be between 1 and 5."

    db, err = _get_db()
    if db is None:
        return False, err

    eval_doc = {
        "emotion_alignment": emotion_alignment,
        "lyric_quality": lyric_quality,
        "music_quality": music_quality,
        "overall_satisfaction": overall_satisfaction,
        "feedback_text": feedback_text.strip(),
        "evaluated_at": datetime.now(timezone.utc),
        "is_human_rating": True,
    }

    try:
        result = db["songs"].update_one(
            {"song_id": song_id},
            {
                "$set": {
                    "evaluation": eval_doc,
                    "rating": overall_satisfaction,
                }
            },
        )
        if result.matched_count == 0:
            return False, f"No song found with id '{song_id}'."
        return True, None
    except Exception as exc:
        return False, f"Failed to save evaluation: {exc}"


def get_all_evaluations() -> tuple[list[dict], str | None]:
    """
    Fetch all songs that have evaluation data populated.
    """
    db, err = _get_db()
    if db is None:
        return [], err

    try:
        cursor = db["songs"].find(
            {"evaluation": {"$ne": None}},
            sort=[("evaluation.evaluated_at", DESCENDING)]
        )
        return [_doc_to_dict(doc) for doc in cursor], None
    except Exception as exc:
        return [], f"Failed to fetch evaluations: {exc}"


def get_evaluation_stats() -> tuple[dict, str | None]:
    """
    Calculate aggregate evaluation metrics across all evaluated songs.
    Returns transparent statistics computed from actual MongoDB documents.
    """
    evals, err = get_all_evaluations()
    if err:
        return {}, err

    total_count = len(evals)
    if total_count == 0:
        return {
            "total_evaluated": 0,
            "avg_emotion_alignment": 0.0,
            "avg_lyric_quality": 0.0,
            "avg_music_quality": 0.0,
            "avg_overall_satisfaction": 0.0,
            "overall_avg": 0.0,
            "rating_counts": {1: 0, 2: 0, 3: 0, 4: 0, 5: 0},
            "emotion_stats": {},
        }, None

    sum_emo = sum(e["evaluation"]["emotion_alignment"] for e in evals if "evaluation" in e and "emotion_alignment" in e["evaluation"])
    sum_lyr = sum(e["evaluation"]["lyric_quality"] for e in evals if "evaluation" in e and "lyric_quality" in e["evaluation"])
    sum_mus = sum(e["evaluation"]["music_quality"] for e in evals if "evaluation" in e and "music_quality" in e["evaluation"])
    sum_sat = sum(e["evaluation"]["overall_satisfaction"] for e in evals if "evaluation" in e and "overall_satisfaction" in e["evaluation"])

    avg_emo = round(sum_emo / total_count, 2)
    avg_lyr = round(sum_lyr / total_count, 2)
    avg_mus = round(sum_mus / total_count, 2)
    avg_sat = round(sum_sat / total_count, 2)
    overall_avg = round((avg_emo + avg_lyr + avg_mus + avg_sat) / 4.0, 2)

    rating_counts = {1: 0, 2: 0, 3: 0, 4: 0, 5: 0}
    for e in evals:
        sat = e.get("evaluation", {}).get("overall_satisfaction")
        if sat in rating_counts:
            rating_counts[sat] += 1

    emo_dict = {}
    for e in evals:
        p_emo = e.get("emotion", {}).get("primary_emotion", "Romantic")
        if p_emo not in emo_dict:
            emo_dict[p_emo] = {"count": 0, "sum_sat": 0, "sum_alignment": 0}
        emo_dict[p_emo]["count"] += 1
        emo_dict[p_emo]["sum_sat"] += e.get("evaluation", {}).get("overall_satisfaction", 0)
        emo_dict[p_emo]["sum_alignment"] += e.get("evaluation", {}).get("emotion_alignment", 0)

    emotion_stats = {}
    for emo, d in emo_dict.items():
        c = d["count"]
        emotion_stats[emo] = {
            "count": c,
            "avg_satisfaction": round(d["sum_sat"] / c, 2),
            "avg_alignment": round(d["sum_alignment"] / c, 2),
        }

    return {
        "total_evaluated": total_count,
        "avg_emotion_alignment": avg_emo,
        "avg_lyric_quality": avg_lyr,
        "avg_music_quality": avg_mus,
        "avg_overall_satisfaction": avg_sat,
        "overall_avg": overall_avg,
        "rating_counts": rating_counts,
        "emotion_stats": emotion_stats,
    }, None

